// <auto-generated />
using FeuerwerkLager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeuerwerkLager.Migrations
{
    [DbContext(typeof(FireworksContext))]
    [Migration("20251125020000_AddLoosePiecesAndFullUnits")]
    partial class AddLoosePiecesAndFullUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FeuerwerkLager.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMultiPart")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NEM")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PiecesPerUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("FeuerwerkLager.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FeuerwerkLager.Models.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FullUnits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoosePieces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ArticleId", "LocationId")
                        .IsUnique();

                    b.ToTable("StockEntries", (string)null);

                    b.ToTable(tb =>
                        {
                            tb.HasCheckConstraint("CK_StockEntries_FullUnits_NonNegative", "[FullUnits] >= 0");
                            tb.HasCheckConstraint("CK_StockEntries_LoosePieces_NonNegative", "[LoosePieces] >= 0");
                        });
                });

            modelBuilder.Entity("FeuerwerkLager.Models.StockEntry", b =>
                {
                    b.HasOne("FeuerwerkLager.Models.Article", "Article")
                        .WithMany("StockEntries")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeuerwerkLager.Models.Location", "Location")
                        .WithMany("StockEntries")
                        .HasForeignKey("LocationId");

                    b.Navigation("Article");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FeuerwerkLager.Models.Article", b =>
                {
                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("FeuerwerkLager.Models.Location", b =>
                {
                    b.Navigation("StockEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
